name: "Reusable CI Workflow"

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
    secrets:
      TOKEN:
        required: true

jobs:
  greet:
    runs-on: ubuntu-latest
    outputs:
      greet_msg: ${{ steps.msg.outputs.greet_msg }}

    steps:
      - name: Generate Message
        id: msg
        run: echo "greet_msg=Hello, ${{ inputs.username }}!" >> $GITHUB_OUTPUT

      - name: Print Token Length
        run: echo "Token length:${{ secrets.TOKEN }} | wc -c"

